### ISSUE TITLE
安装插件报错

### ISSUE THREAD

**Issue by KevinClair** [congqiu/yapi-plugin-notifier#2]
Hello，请教一下具体的安装步骤是什么？
需要做什么前置工作吗？比如说安装什么插件。
1.我这边按照提示的命令，先是运行了`yapi plugin --name yapi-plugin-notifier`;
2.之后报错提示"permession denined"；
3.我用sudo执行了一下命令，但是报了另外的错；
![image](https://user-images.githubusercontent.com/37257651/123948948-8f92f880-d9d4-11eb-9d07-bcabb6df0574.png)
4.之后我按照提示的方法
![image](https://user-images.githubusercontent.com/37257651/123948985-9de11480-d9d4-11eb-90ba-719d89ee0c55.png)
执行了1，2步成功，但是到第三步的时候，报错和上面的一样；
![image](https://user-images.githubusercontent.com/37257651/123949044-b0f3e480-d9d4-11eb-8a3d-b617879720d0.png)
5.请问一下我是没有安装某个插件吗？还是什么？另外我的config.json里面的配置已经改了。

**Comment by 467892746** [comment]
使用yapi 1.9.2版本。按照这个issues替换掉配置文件。https://github.com/YMFE/yapi/issues/2109

**Comment by 467892746** [comment]
使用yapi 1.9.2版本。按照这个issues替换掉配置文件。[https://github.com/YMFE/yapi/issues/2109](url)
